/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrunlerimizRouteImport } from './routes/urunlerimiz'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkindaRouteImport } from './routes/hakkinda'
import { Route as IndexRouteImport } from './routes/index'

const UrunlerimizRoute = UrunlerimizRouteImport.update({
  id: '/urunlerimiz',
  path: '/urunlerimiz',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkindaRoute = HakkindaRouteImport.update({
  id: '/hakkinda',
  path: '/hakkinda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
  '/katalog': typeof KatalogRoute
  '/urunlerimiz': typeof UrunlerimizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
  '/katalog': typeof KatalogRoute
  '/urunlerimiz': typeof UrunlerimizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
  '/katalog': typeof KatalogRoute
  '/urunlerimiz': typeof UrunlerimizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hakkinda' | '/iletisim' | '/katalog' | '/urunlerimiz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hakkinda' | '/iletisim' | '/katalog' | '/urunlerimiz'
  id: '__root__' | '/' | '/hakkinda' | '/iletisim' | '/katalog' | '/urunlerimiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HakkindaRoute: typeof HakkindaRoute
  IletisimRoute: typeof IletisimRoute
  KatalogRoute: typeof KatalogRoute
  UrunlerimizRoute: typeof UrunlerimizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urunlerimiz': {
      id: '/urunlerimiz'
      path: '/urunlerimiz'
      fullPath: '/urunlerimiz'
      preLoaderRoute: typeof UrunlerimizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkinda': {
      id: '/hakkinda'
      path: '/hakkinda'
      fullPath: '/hakkinda'
      preLoaderRoute: typeof HakkindaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HakkindaRoute: HakkindaRoute,
  IletisimRoute: IletisimRoute,
  KatalogRoute: KatalogRoute,
  UrunlerimizRoute: UrunlerimizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
